src/main.py:90: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(f)
src/main.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(f)
src/main.py:59: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  if isinstance(v, collections.Mapping):
[INFO 18:09:58] root Saving to FileStorageObserver in /home/ubuntu/Egemen/pymarl2/results/sacred/uav_env/full_obs.
[WARNING 18:09:59] root Changed type of config entry "env_args.observability" from str to int
[DEBUG 18:09:59] pymarl Using capture mode "no"
[INFO 18:09:59] pymarl Running command 'my_main'
[INFO 18:09:59] pymarl Started run with ID "27"
[DEBUG 18:09:59] pymarl Starting Heartbeat
[DEBUG 18:09:59] my_main Started
[INFO 18:09:59] my_main Experiment Parameters:
[INFO 18:09:59] my_main 

{   'action_selector': 'epsilon_greedy',
    'agent': 'n_rnn',
    'agent_output_type': 'q',
    'batch_size': 128,
    'batch_size_run': 8,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '',
    'critic_lr': 0.0005,
    'env': 'uav_env',
    'env_args': {   'grid_shape': [   50,
                                      50],
                    'map_name': 'uav_env',
                    'n_agents': 5,
                    'obs_last_action': False,
                    'observability': 0,
                    'observe_ids': False,
                    'observe_one_hot': False,
                    'seed': 253594479},
    'epsilon_anneal_time': 100000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'estimation': False,
    'estimation_step_size': 5,
    'estimation_threshold': 20,
    'evaluate': False,
    'gain': 0.01,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hypernet_embed': 64,
    'label': 'default_label',
    'learner': 'nq_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 10000,
    'lr': 0.001,
    'mac': 'n_mac',
    'mixer': 'qmix',
    'mixing_embed_dim': 32,
    'model_name': 'full_obs',
    'name': 'full_obs',
    'obs_agent_id': False,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'optimizer': 'adam',
    'per_alpha': 0.6,
    'per_beta': 0.4,
    'q_lambda': False,
    'repeat_id': 1,
    'return_priority': False,
    'rnn_hidden_dim': 64,
    'run': 'default',
    'runner': 'parallel',
    'runner_log_interval': 10000,
    'save_model': True,
    'save_model_interval': 500000,
    'save_replay': False,
    'seed': 253594479,
    't_max': 2050000,
    'target_update_interval': 200,
    'td_lambda': 0.6,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 16,
    'use_cuda': True,
    'use_layer_norm': False,
    'use_orthogonal': False,
    'use_per': False,
    'use_tensorboard': False,
    'utility': 'expected'}

pygame 2.6.1 (SDL 2.28.4, Python 3.8.20)
Hello from the pygame community. https://www.pygame.org/contribute.html
No module named 'gfootball'
[INFO 18:10:04] my_main Beginning training for 2050000 timesteps
/home/ubuntu/Egemen/pymarl2/src/components/episode_buffer.py:105: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484810403/work/torch/csrc/utils/tensor_new.cpp:201.)
  v = th.tensor(v, dtype=dtype, device=self.device)
/home/ubuntu/Egemen/pymarl2/src/components/episode_buffer.py:105: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  v = th.tensor(v, dtype=dtype, device=self.device)
[INFO 18:10:07] my_main t_env: 800 / 2050000
[INFO 18:10:07] my_main Estimated time left: 9 minutes, 33 seconds. Time passed: 3 seconds
[INFO 18:10:12] my_main Saving models to results/models/full_obs__2024-11-16_18-09-59/800
[INFO 18:10:42] my_main Recent Stats | t_env:      10400 | Episode:      104
ep_length_mean:          100.0000	epsilon:                   1.0000	return_mean:             774.6875	return_std:              150.1928
test_ep_length_mean:     100.0000	test_return_mean:        528.2500	test_return_std:         369.7500	
[INFO 18:10:45] my_main t_env: 11200 / 2050000
[INFO 18:10:45] my_main Estimated time left: 2 hours, 3 minutes, 18 seconds. Time passed: 40 seconds
[DEBUG 18:10:55] pymarl Stopping Heartbeat
[ERROR 18:10:55] pymarl Failed after 0:00:55!
Mixer Size: 
974.625K
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/pymarl/lib/python3.8/site-packages/sacred/experiment.py", line 263, in run_commandline
    return self.run(cmd_name, config_updates, named_configs, {}, args)
  File "/home/ubuntu/miniconda3/envs/pymarl/lib/python3.8/site-packages/sacred/experiment.py", line 212, in run
    run()
  File "/home/ubuntu/miniconda3/envs/pymarl/lib/python3.8/site-packages/sacred/run.py", line 233, in __call__
    self.result = self.main_function(*args)
  File "/home/ubuntu/miniconda3/envs/pymarl/lib/python3.8/site-packages/sacred/config/captured_function.py", line 48, in captured_function
    result = wrapped(*args, **kwargs)
  File "src/main.py", line 38, in my_main
    run_REGISTRY[_config['run']](_run, config, _log)
  File "/home/ubuntu/Egemen/pymarl2/src/run/run.py", line 54, in run
    run_sequential(args=args, logger=logger)
  File "/home/ubuntu/Egemen/pymarl2/src/run/run.py", line 196, in run_sequential
    learner.train(episode_sample, runner.t_env, episode)
  File "/home/ubuntu/Egemen/pymarl2/src/learners/nq_learner.py", line 108, in train
    chosen_action_qvals = self.mixer(chosen_action_qvals, batch["state"][:, :-1])
  File "/home/ubuntu/miniconda3/envs/pymarl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/Egemen/pymarl2/src/modules/mixers/nmix.py", line 61, in forward
    return y.view(b, t, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [128, 0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/main.py", line 121, in <module>
    ex.run_commandline(params)
  File "/home/ubuntu/miniconda3/envs/pymarl/lib/python3.8/site-packages/sacred/experiment.py", line 290, in run_commandline
    print_filtered_stacktrace()
  File "/home/ubuntu/miniconda3/envs/pymarl/lib/python3.8/site-packages/sacred/utils.py", line 482, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "/home/ubuntu/miniconda3/envs/pymarl/lib/python3.8/site-packages/sacred/utils.py", line 516, in format_filtered_stacktrace
    return ''.join(filtered_traceback_format(tb_exception))
  File "/home/ubuntu/miniconda3/envs/pymarl/lib/python3.8/site-packages/sacred/utils.py", line 562, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'
